language: python
python:
  - 3.4
  - 3.5
  - 3.6
env:
  - DJANGO_VERSION=1.9.13
  - DJANGO_VERSION=1.10.8
  - DJANGO_VERSION=1.11.9
  - DJANGO_VERSION=1.11.10
  - DJANGO_VERSION=1.11.11
# https://docs.djangoproject.com/en/dev/faq/install/#what-python-version-can-i-use-with-django
matrix:
  exclude:
    - env: DJANGO_VERSION=1.9.13
      python: 3.6
    - env: DJANGO_VERSION=1.10.8
      python: 3.6
addons:
  apt_packages:
    - pandoc
branches:
    except:
        - media
before_install:
    - ./pypi_packager.sh
install:
    - pip install -q django==$DJANGO_VERSION
    - pip install -q -e .
    - pip install -q selenium
    - pip install -q coveralls
script:
    - coverage run --source publications_bootstrap publications_bootstrap/tests/__main__.py
after_success:
    - coveralls
