language: python
python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8
env:
  - DJANGO_VERSION=1.11.29
  - DJANGO_VERSION=2.1.15
  - DJANGO_VERSION=2.2.12
# https://docs.djangoproject.com/en/dev/faq/install/#what-python-version-can-i-use-with-django
matrix:
  exclude:
    - env: DJANGO_VERSION=1.11.29
      python: 3.8
    - env: DJANGO_VERSION=2.1.15
      python: 2.7
    - env: DJANGO_VERSION=2.1.15
      python: 3.4
    - env: DJANGO_VERSION=2.1.15
      python: 3.8
    - env: DJANGO_VERSION=2.2.12
      python: 2.7
    - env: DJANGO_VERSION=2.2.12
      python: 3.4
addons:
  apt_packages:
    - pandoc
branches:
    except:
        - media
before_install:
    - ./pypi_packager.sh
install:
    - pip install -q django==$DJANGO_VERSION
    - pip install -q -r requirements/tests.txt
script:
    - black publications_bootstrap --check
    - safety check
    - coverage run --source publications_bootstrap publications_bootstrap/tests/__main__.py
after_success:
    - coveralls
